package com.example.materialcomponents

sealed class Screens(val Route: String){
    object Home: Screens(Route = "Home")
    object AlertBoxList: Screens(Route = "Alert Boxes")
    object AlertBoxSample: Screens(Route = "AlertBoxSample")
    object AlertBoxIcon: Screens(Route = "AlertBoxIcon")
    object DropDownSample: Screens(Route = "Drop Down Menu")
    object TopAppBarList: Screens(Route = "Top App Bars")
    object SampleTopAppBar: Screens(Route = "SampleTopBar")
    object PinnedTopAppBar: Screens(Route = "PinnedTopBar")
    object EnterAlwaysTopAppBar: Screens(Route = "EnterAlwaysTopAppBar")
    object SimpleCenterAlignedTopAppBar: Screens(Route = "SimpleCenterAlignedTopAppBar")
    object ExitUntilCollapsedMediumTopAppBar: Screens(Route = "ExitUntilCollapsedMediumTopAppBar")
    object BottomAppBarWithFAB: Screens(Route = "Bottom App Bars")
    object NavigationBarItemWithBadge: Screens(Route = "Simple Badge Box")
    object SimpleBottomSheetScaffoldSample: Screens(Route = "Bottom Sheet Scaffold")
    object CheckBoxList: Screens(Route = "Check Boxes")
    object CheckboxWithTextSample: Screens(Route = "CheckboxWithTextSample")
    object TriStateCheckboxSample: Screens(Route = "TriStateCheckboxSample")
    object ChipsList: Screens(Route = "Chips")
    object AssistChipSample: Screens(Route = "AssistChipSample")
    object FilterChipWithLeadingIconSample: Screens(Route = "FilterChipWithLeadingIconSample")
    object ChipGroupReflowSample: Screens(Route = "ChipGroupReflowSample")
    object DatePickersList: Screens(Route = "Date Pickers")
    object DatePickerSample: Screens(Route = "DatePickerSample")
    object DateRangePickerSample: Screens(Route = "DateRangePickerSample")
    object ExposedDropdownMenuSample: Screens(Route = "Exposed Drop Down")
    object ListItem: Screens(Route = "List Item")
    object ModalBottomSheet: Screens(Route = "Modal Bottom Sheet")
    object NavigationBarSample: Screens(Route = "NavigationBarSample")
    object ModalNavigationList: Screens(Route = "Navigation Drawer")
    object ModalNavigationDrawerSample: Screens(Route = "ModalNavigationDrawerSample")
    object DismissibleNavigationDrawerSample: Screens(Route = "DismissibleNavigationDrawerSample")
    object NavigationRailSample: Screens(Route = "NavigationRailSample")
    object InputFieldsList: Screens(Route = "Input Fields")
    object SimpleOutlinedTextFieldSample: Screens(Route = "SimpleOutlinedTextFieldSample")
    object SimpleTextFieldSample: Screens(Route = "SimpleTextFieldSample")
    object SearchBarSample: Screens(Route = "SearchBarSample")
    object DockedSearchBarSample: Screens(Route = "DockedSearchBarSample")
    object IndicatorList: Screens(Route = "Indicators")
    object LinearProgressIndicatorSample: Screens(Route = "LinearProgressIndicatorSample")
    object CircularProgressIndicatorSample: Screens(Route = "CircularProgressIndicatorSample")
    object SliderList: Screens(Route = "Sliders")
    object StepsSliderSample: Screens(Route = "StepsSliderSample")
    object RangeSliderSample: Screens(Route = "RangeSliderSample")
    object ScaffoldWithCustomSnackbar: Screens(Route = "Snack Bars")
    object SwipeToDismissListItems: Screens(Route = "Swipe To Dismiss")
    object SwitchSample: Screens(Route = "Switches")
    object LeadingIconTabs: Screens(Route = "Tabs")
    object TimePickerSample: Screens(Route = "Time Picker")
    object EnterAnimations: Screens(Route = "Enter Animations")
    object ExitAnimations: Screens(Route = "Exit Animations")
    object EasingInAnimations: Screens(Route = "Easing In Animations")

}
